services: docker
language: perl
git:
  depth: 3
matrix:
  include:
  - name: "openSUSE/SUSE production perl version, only compile check"
    perl: "5.18"
    env: TESTS=compile
  - name: "testing perl version, static checks"
    perl: "5.26"
    env: TESTS=static
  - name: "testing perl version, unit tests"
    perl: "5.26"
    env: TESTS=unit
  - name: "isotovideo smoke test"
    perl: "5.26"
    env: TESTS=isotovideo
env:
  global:
    - COMMIT_AUTHOR_EMAIL=skynet@open.qa
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libssh2-1-dev
      - parallel
cache:
  directories:
    - $HOME/perl5
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl --always-upgrade-modules
install:
  - make prepare
script:
  - source script/generateLibDocs.sh
  - make test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: $TRAVIS_BUILD_DIR/docs/
  on:
    branch: master
    condition: "$NEW_DEPLOY_NEEDED = 1 && $TESTS = unit"
  target_branch: gh-pages
