#!/bin/sh -e
test_files=$(git ls-files "*tests/*.pm")
unused_opensuse=$(for test in $test_files ; do t=${test#tests/} ; grep -q -L $t products/opensuse/main.pm || echo $test ; done)
unused_sle=$(for test in $test_files ; do t=${test#tests/} ; grep -q -L $t products/sle/main.pm || echo $test ; done)
unused_common=$(for test in $test_files ; do t=${test#tests/} ; grep -q -L $t lib/main_common.pm || echo $test ; done)
# show modules not used in any test plan
(echo "$unused_opensuse" && echo "$unused_sle" && echo "$unused_common") | sort | uniq -c | sort | sed -n 's/^.*3 //p'
